<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        // Ensure test user exists (idempotent)
        \App\Models\User::updateOrCreate(
            ['email' => 'test@example.com'],
            [
                'name' => 'Test User',
                'password' => \Illuminate\Support\Facades\Hash::make('password'),
            ]
        );

        // Patient user account
        \App\Models\User::updateOrCreate(
            ['email' => 'juan.delacruz@email.com'],
            [
                'name' => 'Juan Dela Cruz',
                'password' => \Illuminate\Support\Facades\Hash::make('password'),
            ]
        );

        // Admin user for BicolVax (create or update)
        \App\Models\User::updateOrCreate(
            ['email' => 'bicolvaxclinic@gmail.com'],
            [
                'name' => 'BicolVax Clinic',
                'password' => \Illuminate\Support\Facades\Hash::make('Admin_123'),
                'is_admin' => true,
            ]
        );

        // Seed patients
        $patients = [
            [
                'full_name' => 'Juan Dela Cruz',
                'card_no' => 'BV-2026-0001',
                'case_no' => 'CASE-0001',
                'contact' => '09171234567',
                'age' => 34,
                'email' => 'juan.delacruz@email.com',
                'gender' => 'Male',
                'address' => 'Brgy. San Roque, Naga City, Camarines Sur',
                'weight' => 72.50,
                'cat_category' => 'Category III',
                'treatment_required' => json_encode(['Wound washing', 'RIG', 'Vaccine']),
                'bite_type' => 'Dog bite',
                'place_of_bite' => 'Left hand',
                'source' => 'admin',
                'severity' => 'Severe',
                'generic_name' => 'Purified Vero Cell Rabies Vaccine',
                'route' => 'Intramuscular',
                'brand_name' => 'Verorab',
                'dosage' => '0.5 mL',
                'anti_rabies_dose' => 'Day 0',
                'anti_rabies_date' => '2026-06-01',
                'tetanus_status' => 'Not vaccinated',
                'tetanus_dose' => '0.5 mL',
                'tetanus_date' => '2026-06-01',
                'rabies_immunoglobulin' => 'Yes',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Maria Santos',
                'card_no' => 'BV-2026-0002',
                'case_no' => 'CASE-0002',
                'contact' => '09281234567',
                'age' => 28,
                'email' => 'maria.santos@email.com',
                'gender' => 'Female',
                'address' => 'Brgy. Concepcion, Legazpi City, Albay',
                'weight' => 55.00,
                'cat_category' => 'Category II',
                'treatment_required' => json_encode(['Wound washing', 'Vaccine']),
                'bite_type' => 'Cat scratch',
                'place_of_bite' => 'Right arm',
                'source' => 'web',
                'severity' => 'Moderate',
                'generic_name' => 'Purified Vero Cell Rabies Vaccine',
                'route' => 'Intramuscular',
                'brand_name' => 'Verorab',
                'dosage' => '0.5 mL',
                'anti_rabies_dose' => 'Day 0',
                'anti_rabies_date' => '2026-06-05',
                'tetanus_status' => 'Vaccinated',
                'tetanus_dose' => 'N/A',
                'tetanus_date' => '2026-06-05',
                'rabies_immunoglobulin' => 'No',
                'status' => 'not_approved',
            ],
            [
                'full_name' => 'Pedro Reyes',
                'card_no' => 'BV-2026-0003',
                'case_no' => 'CASE-0003',
                'contact' => '09351234567',
                'age' => 45,
                'email' => 'pedro.reyes@email.com',
                'gender' => 'Male',
                'address' => 'Brgy. Dinaga, Iriga City, Camarines Sur',
                'weight' => 80.00,
                'cat_category' => 'Category III',
                'treatment_required' => json_encode(['Wound washing', 'RIG', 'Vaccine']),
                'bite_type' => 'Dog bite',
                'place_of_bite' => 'Left leg',
                'source' => 'admin',
                'severity' => 'Severe',
                'generic_name' => 'Purified Chick Embryo Cell Vaccine',
                'route' => 'Intramuscular',
                'brand_name' => 'Rabipur',
                'dosage' => '1.0 mL',
                'anti_rabies_dose' => 'Day 3',
                'anti_rabies_date' => '2026-06-03',
                'tetanus_status' => 'Not vaccinated',
                'tetanus_dose' => '0.5 mL',
                'tetanus_date' => '2026-06-03',
                'rabies_immunoglobulin' => 'Yes',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Ana Villanueva',
                'card_no' => 'WEB-2026-0004',
                'case_no' => 'CASE-0004',
                'contact' => '09451234567',
                'age' => 22,
                'email' => 'ana.villanueva@email.com',
                'gender' => 'Female',
                'address' => 'Brgy. Tabuco, Naga City, Camarines Sur',
                'weight' => 50.00,
                'cat_category' => 'Category II',
                'treatment_required' => json_encode(['Wound washing', 'Vaccine']),
                'bite_type' => 'Dog bite',
                'place_of_bite' => 'Right foot',
                'source' => 'web',
                'severity' => 'Moderate',
                'generic_name' => 'Purified Vero Cell Rabies Vaccine',
                'route' => 'Intradermal',
                'brand_name' => 'Verorab',
                'dosage' => '0.1 mL',
                'anti_rabies_dose' => 'Day 0',
                'anti_rabies_date' => '2026-06-10',
                'tetanus_status' => 'Vaccinated',
                'tetanus_dose' => 'N/A',
                'tetanus_date' => '2026-06-10',
                'rabies_immunoglobulin' => 'No',
                'status' => 'not_approved',
            ],
            [
                'full_name' => 'Carlos Bautista',
                'card_no' => 'BV-2026-0005',
                'case_no' => 'CASE-0005',
                'contact' => '09551234567',
                'age' => 38,
                'email' => 'carlos.bautista@email.com',
                'gender' => 'Male',
                'address' => 'Brgy. Peñafrancia, Naga City, Camarines Sur',
                'weight' => 68.00,
                'cat_category' => 'Category III',
                'treatment_required' => json_encode(['Wound washing', 'RIG', 'Vaccine']),
                'bite_type' => 'Dog bite',
                'place_of_bite' => 'Face',
                'source' => 'admin',
                'severity' => 'Severe',
                'generic_name' => 'Purified Vero Cell Rabies Vaccine',
                'route' => 'Intramuscular',
                'brand_name' => 'Verorab',
                'dosage' => '0.5 mL',
                'anti_rabies_dose' => 'Day 7',
                'anti_rabies_date' => '2026-06-08',
                'tetanus_status' => 'Not vaccinated',
                'tetanus_dose' => '0.5 mL',
                'tetanus_date' => '2026-06-08',
                'rabies_immunoglobulin' => 'Yes',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Rosalie Gonzales',
                'card_no' => 'BV-2026-0006',
                'case_no' => 'CASE-0006',
                'contact' => '09651234567',
                'age' => 50,
                'email' => 'rosalie.gonzales@email.com',
                'gender' => 'Female',
                'address' => 'Brgy. Sagrada, Daraga, Albay',
                'weight' => 62.00,
                'cat_category' => 'Category I',
                'treatment_required' => json_encode(['Wound washing']),
                'bite_type' => 'Cat bite',
                'place_of_bite' => 'Right hand',
                'source' => 'admin',
                'severity' => 'Mild',
                'generic_name' => 'Purified Vero Cell Rabies Vaccine',
                'route' => 'Intramuscular',
                'brand_name' => 'Verorab',
                'dosage' => '0.5 mL',
                'anti_rabies_dose' => 'Day 0',
                'anti_rabies_date' => '2026-06-12',
                'tetanus_status' => 'Vaccinated',
                'tetanus_dose' => 'N/A',
                'tetanus_date' => '2026-06-12',
                'rabies_immunoglobulin' => 'No',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Roberto Mendoza',
                'card_no' => 'WEB-2026-0007',
                'case_no' => 'CASE-0007',
                'contact' => '09751234567',
                'age' => 60,
                'email' => 'roberto.mendoza@email.com',
                'gender' => 'Male',
                'address' => 'Brgy. Centro, Sorsogon City, Sorsogon',
                'weight' => 75.00,
                'cat_category' => 'Category III',
                'treatment_required' => json_encode(['Wound washing', 'RIG', 'Vaccine']),
                'bite_type' => 'Dog bite',
                'place_of_bite' => 'Left thigh',
                'source' => 'web',
                'severity' => 'Severe',
                'generic_name' => 'Purified Chick Embryo Cell Vaccine',
                'route' => 'Intramuscular',
                'brand_name' => 'Rabipur',
                'dosage' => '1.0 mL',
                'anti_rabies_dose' => 'Day 0',
                'anti_rabies_date' => '2026-06-15',
                'tetanus_status' => 'Not vaccinated',
                'tetanus_dose' => '0.5 mL',
                'tetanus_date' => '2026-06-15',
                'rabies_immunoglobulin' => 'Yes',
                'status' => 'not_approved',
            ],
            [
                'full_name' => 'Lorna Aquino',
                'card_no' => 'BV-2026-0008',
                'case_no' => 'CASE-0008',
                'contact' => '09851234567',
                'age' => 18,
                'email' => 'lorna.aquino@email.com',
                'gender' => 'Female',
                'address' => 'Brgy. San Felipe, Naga City, Camarines Sur',
                'weight' => 48.00,
                'cat_category' => 'Category II',
                'treatment_required' => json_encode(['Wound washing', 'Vaccine']),
                'bite_type' => 'Dog bite',
                'place_of_bite' => 'Left ankle',
                'source' => 'admin',
                'severity' => 'Moderate',
                'generic_name' => 'Purified Vero Cell Rabies Vaccine',
                'route' => 'Intradermal',
                'brand_name' => 'Verorab',
                'dosage' => '0.1 mL',
                'anti_rabies_dose' => 'Day 0',
                'anti_rabies_date' => '2026-06-18',
                'tetanus_status' => 'Vaccinated',
                'tetanus_dose' => 'N/A',
                'tetanus_date' => '2026-06-18',
                'rabies_immunoglobulin' => 'No',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Ricardo Flores',
                'card_no' => 'BV-2026-0009',
                'case_no' => 'CASE-0009',
                'contact' => '09951234567',
                'age' => 42,
                'email' => 'ricardo.flores@email.com',
                'gender' => 'Male',
                'address' => 'Brgy. Bagumbayan, Tabaco City, Albay',
                'weight' => 85.00,
                'cat_category' => 'Category III',
                'treatment_required' => json_encode(['Wound washing', 'RIG', 'Vaccine']),
                'bite_type' => 'Dog bite',
                'place_of_bite' => 'Right shoulder',
                'source' => 'admin',
                'severity' => 'Severe',
                'generic_name' => 'Purified Vero Cell Rabies Vaccine',
                'route' => 'Intramuscular',
                'brand_name' => 'Verorab',
                'dosage' => '0.5 mL',
                'anti_rabies_dose' => 'Day 14',
                'anti_rabies_date' => '2026-06-15',
                'tetanus_status' => 'Not vaccinated',
                'tetanus_dose' => '0.5 mL',
                'tetanus_date' => '2026-06-01',
                'rabies_immunoglobulin' => 'Yes',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Gloria Ramos',
                'card_no' => 'WEB-2026-0010',
                'case_no' => 'CASE-0010',
                'contact' => '09091234567',
                'age' => 30,
                'email' => 'gloria.ramos@email.com',
                'gender' => 'Female',
                'address' => 'Brgy. Magsaysay, Daet, Camarines Norte',
                'weight' => 58.00,
                'cat_category' => 'Category II',
                'treatment_required' => json_encode(['Wound washing', 'Vaccine']),
                'bite_type' => 'Cat scratch',
                'place_of_bite' => 'Left forearm',
                'source' => 'web',
                'severity' => 'Moderate',
                'generic_name' => 'Purified Vero Cell Rabies Vaccine',
                'route' => 'Intramuscular',
                'brand_name' => 'Verorab',
                'dosage' => '0.5 mL',
                'anti_rabies_dose' => 'Day 0',
                'anti_rabies_date' => '2026-06-20',
                'tetanus_status' => 'Vaccinated',
                'tetanus_dose' => 'N/A',
                'tetanus_date' => '2026-06-20',
                'rabies_immunoglobulin' => 'No',
                'status' => 'not_approved',
            ],
        ];

        foreach ($patients as $patient) {
            \App\Models\Patient::updateOrCreate(
                ['card_no' => $patient['card_no']],
                $patient
            );
        }
    }
}
